### ISSUE TITLE
/bin/sh: theme: command not found

### ISSUE THREAD

**Issue by smilburn1990** [Youhan/shopify-vuejs-starter-theme#2]
Hello,

Firstly I would like to say this is amazing - thanks for making this solution possible.

I am having a problem with the setup and was wondering what I am doing wrong.

- I am on the 14-day free trial
- I have uploaded the theme to Shopify and have published it
- I have cloned, ran `yarn`, and added the settings as follows but still get the error when running `yarn dev` - `/bin/sh: theme: command not found`

`development:
  password: *****
  theme_id: 118810312881
  store: smilburns.myshopify.com
  timeout: 3m0s
`
Is the password for this the password for my account or the storefront preferences? I have tried both and get the same error.

If you could help me that would be great. Thanks again!!

NOTE: Might be worth mentioning the following risks too...

`
risk - There are upcoming breaking changes: removeDeprecatedGapUtilities, purgeLayersByDefault, defaultLineHeights, standardFontWeights
risk - We highly recommend opting-in to these changes now to simplify upgrading Tailwind in the future.
risk - https://tailwindcss.com/docs/upcoming-changes
`

**Comment by Youhan** [comment]
You need to install the [Shopify theme kit](https://github.com/Shopify/themekit) to solve the `yarn dev` issue.

**Comment by Youhan** [comment]
The risk is just a warning that TailwindCSS prints out.
